image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - docker-compose up &
  - sleep 120 && java -jar ./artifacts/aqa-shop.jar &

build_script:
  - sleep 120 && chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info