image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

services:
  - docker

install:
  - sudo curl -SL https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose -f docker-compose.yml up -d
  - sleep 20
  - java -jar ./artifacts/aqa-shop.jar --spring.datasource.url=jdbc:mysql://localhost:3366/app &
  - sleep 20

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:mysql://localhost:3366/app
  - sudo docker-compose down