image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

services:
  - docker

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose up
  - sleep 20
  - java -jar ./artifacts/aqa-shop.jar.jar
  - chmod +x gradlew
  - sleep 20

build_script:

  - ./gradlew test --info -Dselenide.headless=true